### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Ouya-Bytes** [XiaoyuShi97/VideoFlow#18]
I have trained the MOF model using 2x32GB 100V, and the parameters are set to
_CN.batch_size = 4 or 8,
_CN.image_size = [432, 960],
_CN.MOFNetStack.corr_fn = 'default' or use 'efficient',
_CN.MOFNetStack.decoder_depth = 6 or 12,
others parms is defualt in sintel_multiframes.py,
But get error:
>>>>>>>>>>>>>>>>>>>>
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/Flow3D/VideoFlow/core/Networks/MOFNetStack/network.py", line 172, in forward
    cnet = self.cnet(images[:, 1:N-1, ...].reshape(B*(N-2), 3, H, W))
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/Flow3D/VideoFlow/core/Networks/encoders.py", line 31, in forward
    x = blk(x, size)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/timm/models/twins.py", line 217, in forward
    x = x + self.drop_path(self.attn(self.norm1(x), size))
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/timm/models/twins.py", line 188, in forward
    attn = (q @ k.transpose(-2, -1)) * self.scale
RuntimeError: CUDA out of memory. Tried to allocate 926.00 MiB (GPU 0; 31.75 GiB total capacity; 29.04 GiB already allocated; 863.69 MiB free; 29.68 GiB reserved in total by PyTorch)

Debug the scripts, error occurred in the line: 
'''
            with autocast(enabled=self.cfg.mixed_precision):
                net, motion_hidden_state, up_mask, delta_flow = self.update_block(net, motion_hidden_state, inp, forward_corr, backward_corr, forward_flow, backward_flow, forward_coords0, attention, bs=B)
'''

How should I resolve this issue?

--------------------------------

Training the BOF model has same error:
File "train_BOFNet.py", line 83, in train
    flow_predictions = model(images, output)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/Flow3D/VideoFlow/core/Networks/BOFNet/network.py", line 103, in forward
    corr_fn_23 = CorrBlock(fmap2, fmap3, num_levels=self.cfg.corr_levels, radius=self.cfg.corr_radius)
  File "/workspace/Flow3D/VideoFlow/core/Networks/BOFNet/corr.py", line 82, in __init__
    corr = CorrBlock.corr(fmap1, fmap2)
  File "/workspace/Flow3D/VideoFlow/core/Networks/BOFNet/corr.py", line 121, in corr
    corr = torch.matmul(fmap1.transpose(1, 2), fmap2)
RuntimeError: CUDA out of memory. Tried to allocate 1.25 GiB (GPU 0; 31.75 GiB total capacity; 29.41 GiB already allocated; 225.69 MiB free; 30.30 GiB reserved in total by PyTorch)

**Comment by Ouya-Bytes** [comment]
Whether can give some solutions for this bug, thanks!

**Comment by XiaoyuShi97** [comment]
Hi. You may consider decrease the training resolution. I will check if gradient checkpointing can help, but it may take some time.

**Comment by Ouya-Bytes** [comment]
Thanks for you reply.  I used the default configuration and the corresponding openning sources dataset to training the model. But the infer stage is performed normally。

**Comment by Ouya-Bytes** [comment]
Possibly, the utilization of "twins_svt_large" by the encoder led to inflated parameter weights. I opted to switch to "twins_svt_small," adjusted the output hidden dimensions to 256, reduced the batch size, and employed 2x32 V100. Finally, the model trained successfully.
